//! Hardware abstraction layer for B-G431B-ESC1 board

pub mod peripherals;
pub mod resources;

// Re-export types generated by assign_resources
pub use resources::{AssignedResources, HallResources, MotorResources};
