[package]
name = "oxifoc-virtual"
version = "0.1.0"
edition = "2024"
description = "Virtual motor controller device with ergot protocol over TCP"

[dependencies]
oxifoc-core = { workspace = true, features = [
    "runtime",
    "virtual-motor",
    "storage",
    "std",
    "log",
    "delivery",
] }

ergot = { workspace = true, features = ["tokio-std"] }
tokio = { workspace = true }
critical-section = { version = "1.2", features = ["std"] }
sequential-storage = { version = "7.1", features = ["postcard", "_test"] }
heapless = "0.9"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tokio-util = { version = "0.7.18", features = ["rt"] }
socket2 = "0.6.3"
rand = "0.9"
