[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = ["bash", "../scripts/probe_run_f405.sh"]
rustflags = ["-C", "target-feature=+vfp2,-fp64"]

[env]
# Default to chatty defmt logs while bringup
DEFMT_LOG = "debug"
