//! App timebase: rtic-monotonics on TIM5 at 1 MHz (32-bit counter).
//!
//! Part of the RTIC port experiment's "shrink embassy-time" step: every
//! delay/timeout/timestamp the f405 crate controls runs on this monotonic.
//! embassy-time (TIM2 driver + generic queue) stays in the build, but only
//! for consumers we don't control on this branch: ergot (liveness
//! timestamps, USB toolkit timeouts, seed-router lease timing — its
//! `embassy-usb-v0_6`/`nostd-seed-router` features hard-depend on it) and
//! oxifoc-core's detection wrappers (`embassy_hw` hardcodes `EmbassyTimer`)
//! plus the current-offset calibrate delay in `foc::sensors`.
//!
//! The TIM5 interrupt handler is generated by the macro below; its NVIC
//! priority is set by rtic-monotonics to sit just above RTIC's async
//! dispatchers (it reads RTIC's `RTIC_ASYNC_MAX_LOGICAL_PRIO`), far below
//! the FOC/hall hardware tasks.

use rtic_monotonics::stm32::prelude::*;

stm32_tim5_monotonic!(Mono, 1_000_000);

/// oxifoc-core async-delay implementation backed by the TIM5 monotonic
/// (the RTIC-branch replacement for `oxifoc_core::timer::EmbassyTimer`).
pub struct MonoTimer;

impl oxifoc_core::timer::Timer for MonoTimer {
    async fn after_millis(ms: u64) {
        Mono::delay(ms.millis()).await;
    }

    async fn after_micros(us: u64) {
        Mono::delay(us.micros()).await;
    }
}
