[package]
name = "oxifoc-host-lib"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
desktop = [
    "dep:probe-rs",
    "dep:tokio-serial",
    "ergot/tokio-serial-v5",
]

[dependencies]
oxifoc-core = { workspace = true, features = ["icd", "storage", "delivery"] }
ergot = { workspace = true, features = ["tokio-std", "nusb-v0_1", "defmtlog"] }

tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io"] }

# Desktop-only transports
tokio-serial = { version = "5.4.4", optional = true }
probe-rs = { version = "0.28", optional = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-log = "0.2"

anyhow = { workspace = true }
crossbeam-channel = { workspace = true }
defmt-decoder = "1.0"
defmt-parser = "1.0"
serde = { workspace = true }
toml = { workspace = true }
tokio-stream = "0.1.18"
bytes = "1.11.1"
futures = "0.3.32"
bluest = { git = "https://github.com/okhsunrog/bluest", rev = "9cb9dbcad63d7d2ffe18a20f87b7ffe1cb670537", features = ["unstable"] }
serde_json = "1.0.150"

[lints]
workspace = true
