//! Hardware abstraction layer for NUCLEO-G474RE + X-NUCLEO-IHM08M1 board

pub mod peripherals;
pub mod resources;

// Re-export types generated by assign_resources
pub use resources::{AssignedResources, HallResources, MotorResources, StorageResources};
