//! Hardware abstraction layer for NUCLEO-G474RE board

pub mod peripherals;
pub mod resources;

// Re-export types generated by assign_resources
// Motor and Hall resources are commented out until IHM08M1 shield is connected
pub use resources::{AssignedResources, StorageResources};
// pub use resources::{HallResources, MotorResources};
