[package]
name = "oxifoc-host-slint"
version = "0.1.0"
edition = "2024"

[dependencies]
oxifoc-host-lib = { path = "../oxifoc-host-lib" }
oxifoc-core = { path = "../oxifoc-core", features = ["icd", "virtual-motor"] }
slint-wgpu-plot = { path = "../slint-wgpu-plot" }
slint = { workspace = true, features = ["backend-winit", "renderer-femtovg-wgpu", "accessibility"] }
crossbeam-channel = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
