//! Config CLI: the generic group schema + read-modify-write live in
//! `oxifoc_host_lib::ops::config` (shared with the GUI); this module only
//! adds the CLI-only presentation — `config dump`, including the `--rust`
//! `baked_config.rs` emission.

use anyhow::Result;
use oxifoc_host_lib::HostRuntime;
use serde_json::Value;

// Re-export the shared, presentation-agnostic config ops so existing call
// sites (`config_cli::parse_group`, `config_cli::current_value`, …) and the
// `detect` module keep working unchanged.
pub use oxifoc_host_lib::ops::config::{
    GROUPS, config_snapshot, current_value, group_value, parse_group, read_group, send_write,
    set_fields, write_from_value,
};

/// Dump every config group; `--rust` renders a ready-to-paste
/// `baked_config.rs` body for the baked firmware profile.
pub fn dump_config(runtime: &HostRuntime, rust: bool, json_mode: bool) -> Result<()> {
    let cmd = &runtime.cmd_tx;
    if json_mode && !rust {
        let mut obj = serde_json::Map::new();
        for (name, group) in GROUPS {
            let snapshot = read_group(cmd, group)?;
            let v = snapshot
                .value
                .as_ref()
                .and_then(group_value)
                .unwrap_or(Value::Null);
            obj.insert(name.to_string(), v);
        }
        println!("{:#}", Value::Object(obj));
        return Ok(());
    }

    let mut read = Vec::new();
    for (_, g) in GROUPS {
        read.push((g, read_group(cmd, g)?));
    }

    if !rust {
        for (g, resp) in &read {
            match &resp.value {
                Some(value) => println!(
                    "{g:?} (revision {}, {}): {value:?}",
                    resp.revision,
                    if resp.persisted {
                        "persisted"
                    } else {
                        "volatile"
                    }
                ),
                None => println!("{g:?} (revision {}): (not configured)", resp.revision),
            }
        }
        return Ok(());
    }

    // Rust emission: via the JSON representation so the output stays in
    // sync with the structs without per-field format strings here.
    println!("//! Compiled-in configuration for the baked profile (`storage` feature off).");
    println!("//!");
    println!("//! Generated by `oxifoc-host-cli config dump --rust`. Regenerate after");
    println!("//! re-detection or re-tuning, then rebuild and reflash.");
    println!();
    println!("use oxifoc_core::storage::*;");
    println!();
    println!("/// The baked configuration.");
    println!("pub fn baked() -> RuntimeConfig {{");
    println!("    RuntimeConfig {{");
    for (name, group) in GROUPS {
        let field = name.replace('-', "_");
        let resp = read
            .iter()
            .find(|(g, _)| format!("{g:?}") == format!("{group:?}"))
            .and_then(|(_, r)| r.value.as_ref());
        match resp.and_then(group_value) {
            Some(v) => {
                let struct_name = rust_struct_name(name);
                println!("        {field}: Some({struct_name} {{");
                if let Some(obj) = v.as_object() {
                    for (k, val) in obj {
                        println!("            {k}: {},", rust_literal(val));
                    }
                }
                println!("        }}),");
            }
            None => println!("        {field}: None,"),
        }
    }
    println!("    }}");
    println!("}}");
    Ok(())
}

fn rust_struct_name(group: &str) -> &'static str {
    match group {
        "motor-params" => "MotorParamsConfig",
        "hall-calibration" => "HallCalibrationConfig",
        "dc-offsets" => "DcOffsetsConfig",
        "current-limits" => "CurrentLimitsConfig",
        "voltage-limits" => "VoltageLimitsConfig",
        "pwm-config" => "PwmConfigStored",
        "pi-gains" => "PiGainsConfig",
        "hall-tuning" => "HallTuningConfig",
        "failsafe" => "FailsafeConfigStored",
        "velocity" => "VelocityConfigStored",
        "derating" => "DeratingConfigStored",
        _ => unreachable!(),
    }
}

/// Render a JSON value as a Rust literal for baked_config emission.
fn rust_literal(v: &Value) -> String {
    match v {
        Value::Number(n) => {
            // f32 fields must keep a float literal even for round values.
            if n.is_f64() {
                let f = n.as_f64().unwrap() as f32;
                format!("{f:?}")
            } else {
                format!("{n}")
            }
        }
        Value::Bool(b) => format!("{b}"),
        Value::Array(items) => {
            let inner: Vec<String> = items.iter().map(rust_literal).collect();
            format!("[{}]", inner.join(", "))
        }
        other => format!("{other}"),
    }
}
