[package]
name = "oxifoc-host-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
oxifoc-host-lib = { path = "../oxifoc-host-lib" }
oxifoc-core = { workspace = true, features = ["icd"] }
anyhow = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
serde_json = "1.0.150"
parquet = { version = "59.0.0", default-features = false, features = ["zstd"] }
serde = { workspace = true, features = ["derive"] }
