//! Hardware abstraction layer for STM32F405 VESC-layout boards
//! (Cheap FOCer 2 / Simple FOCer 2 and VESC 6 MK5 + clones)

pub mod drv8301;
pub mod peripherals;
pub mod resources;

#[cfg(feature = "board-vesc6-mk5")]
use embassy_stm32::gpio::{Level, Output, Speed};

// Re-export types generated by assign_resources
#[cfg(feature = "board-vesc6-mk5")]
pub use resources::BoardCtrlResources;
pub use resources::{
    AssignedResources, DrvResources, HallResources, MotorResources, UartResources,
};

/// Board-control outputs that must stay driven for the whole run — dropping
/// an embassy `Output` disconnects the pin, so the caller keeps this alive.
#[cfg(feature = "board-vesc6-mk5")]
pub struct BoardCtrlPins {
    _shutdown_latch: Output<'static>,
    _current_filter: Output<'static>,
    _phase_filter: Output<'static>,
}

/// MK5 early board init — call as soon as resources are split.
///
/// - PC5 shutdown latch HIGH: the power button only bridges power until
///   firmware holds this pin; releasing the button before we get here
///   powers the board off.
/// - PD2 CURRENT_FILTER HIGH: RC filter on the current-sense path (VESC
///   enables it in HW_EARLY_INIT), must be on before DC-offset calibration.
/// - PC13 PHASE_FILTER HIGH: RC filters on SENS1-3 — the reason
///   `BOARD.phase_sense.has_filters` is true on this board.
#[cfg(feature = "board-vesc6-mk5")]
pub fn board_early_init(r: BoardCtrlResources) -> BoardCtrlPins {
    let pins = BoardCtrlPins {
        _shutdown_latch: Output::new(r.pc5, Level::High, Speed::Low),
        _current_filter: Output::new(r.pd2, Level::High, Speed::Low),
        _phase_filter: Output::new(r.pc13, Level::High, Speed::Low),
    };
    defmt::info!("MK5 board ctrl: shutdown latch PC5=1, current filter PD2=1, phase filter PC13=1");
    pins
}
