//! Hardware abstraction layer for Simple FOCer 2 (STM32F405)

pub mod peripherals;
pub mod resources;

// Re-export types generated by assign_resources
pub use resources::{AssignedResources, HallResources, MotorResources};
